name: Combine Repositories

on:
  push:
    branches:
      - main

jobs:
  combine_repos:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout private repo
      uses: actions/checkout@v2
      with:
        repository: KeyAuth/keyauth-enterprise
        token: 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
        
    - name: Checkout public repo
      uses: actions/checkout@v2
      with:
        repository: KeyAuth/KeyAuth-Source-Code
        ref: main
        path: public-repo
        token: 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

    - name: Combine repositories
      run: |
        git config --global user.email "agentreachout@keyauth.cc"
        git config --global user.name "KeyAuth LLC"
        git config advice.addIgnoredFile false
        git checkout -b combo
        
        rsync -a --exclude '.git' public-repo/ .
        
        git add .
        git status --porcelain | grep -e '\.yml$' | cut -c 4- | xargs -r git reset
        git commit -m "Combine main branch of keyauth-enterprise with KeyAuth-Source-Code"
        git fetch origin main
        git checkout main
        git merge origin/main
        # Resolve conflicts if any
        git add .
        git commit -m "Merge remote changes" || true
        git checkout combo
        git push -f origin combo
